apiVersion: v2
name: thalassa-objectstorage-manager
description: Helm chart for deploying the Thalassa Cloud Object Storage Manager
type: application
version: 1.0.0
appVersion: "1.0.0"
sources:
  - 'https://github.com/thalassa-cloud/thalassa-objectstorage-manager'
