name: E2E Tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test-e2e:
    name: Run on Ubuntu
    runs-on: ubuntu-latest
    # Live Thalassa API credentials are optional. Without E2E_THALASSA_ENABLED=true
    # the suite skips in BeforeSuite (Kind is still created by make setup-test-e2e).
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          fetch-depth: 0
      - uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6.1.0
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Install the latest version of kind
        run: |
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/latest/kind-linux-$(go env GOARCH)
          chmod +x ./kind
          sudo mv ./kind /usr/local/bin/kind

      - name: Verify kind installation
        run: kind version

      - name: Running Test e2e
        env:
          E2E_THALASSA_ENABLED: ${{ secrets.E2E_THALASSA_ENABLED }}
          E2E_THALASSA_ORGANISATION: ${{ secrets.E2E_THALASSA_ORGANISATION }}
          E2E_THALASSA_TOKEN: ${{ secrets.E2E_THALASSA_TOKEN }}
          E2E_THALASSA_URL: ${{ secrets.E2E_THALASSA_URL }}
          E2E_THALASSA_REGION: ${{ secrets.E2E_THALASSA_REGION }}
        run: |
          go mod tidy
          make test-e2e
